apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: catnip-deployment
  labels:
    app: catnip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catnip
  template:
    metadata:
      labels:
        app: catnip
    spec:
      containers:
      - name: catnip
        image: russest3/catnip:latest
        ports:
        - containerPort: 8000
