apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jenkins 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:      
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.67
        ports:
        - containerPort: 8080
        - containerPort: 50000
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        env:
        - name: JENKINS_OPTS
          value: ''
        - name: JAVA_OPTS
          value: '-Xmx700m'
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-pv                
      volumes:
      - name: jenkins-pv
        persistentVolumeClaim:
          claimName: jenkins-pv-claim