apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:latest
    ports:    
    - containerPort: 8080
    - containerPort: 50000
    readinessProbe:
      httpGet:
        path: /login
        port: 8080
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 2
      failureThreshold: 5
    env:
      - name: JENKINS_OPTS
        value: ''
      - name: JAVA_OPTS
        value: '-Xmx700m'
    volumeMounts:
      - mountPath: /home/admin/jenkins_home
        name: jenkins-pv
  volumes:
      - name: jenkins-pv
        awsElasticBlockStore:
          volumeID: vol-082af71fcfa89bc31
          fsType: ext4